version: '3.7'

services:
  django:
    build: ./backend
    command: ["python", "manage.py", "runserver", "0.0.0.0:8001"]
    volumes:
      - ./backend:/app/backend
    ports:
      - "8001:8001"

  frontend:
    build: ./frontend
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    ports:
      - '8081:8080'
