# Generated by Django 3.0.7 on 2020-06-09 21:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='Descrição da tarefa')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data da criação')),
                ('conclusion_date', models.DateTimeField(verbose_name='Data da conclusão')),
                ('was_completed', models.BooleanField(default=False, verbose_name='Foi completada')),
            ],
        ),
    ]
