# Generated by Django 3.0.7 on 2020-06-11 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='conclusion_date',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Data da conclusão'),
        ),
    ]
